# Generated by Django 2.0.6 on 2019-10-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20191004_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
