# Generated by Django 2.0.6 on 2019-10-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_usersignup_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='roleId',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='isverified',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='roleId',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='userEmail',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='roleName',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='otpcolumn',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='otpconfirmation',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='otptime',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userAddress',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userAge',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userFullName',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userMobile',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userPassword',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='userState',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='usertoken',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='is_verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otp',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otp_time',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='token',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_age',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_fullname',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_mobile',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='user_state',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='verify_link',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
