# Generated by Django 2.0.6 on 2019-10-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20191013_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='user_image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
