# Generated by Django 2.0.6 on 2019-10-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20191016_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='role',
            new_name='role_id',
        ),
    ]
