# Generated by Django 2.0.6 on 2019-10-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuserapp', '0002_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='isverified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otpcolumn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otpconfirmation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='otptime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
